apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: yotamdavid/ferari_docker
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yotam  # Replace with your desired MySQL root password
            - name: MYSQL_DATABASE  # Corrected line with a space after the dash
              value: site_entries
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          emptyDir: {}
