apiVersion: batch/v1
kind: Job
metadata:
  name: init-db-job
spec:
  template:
    spec:
      containers:
        - name: init-db
          image: yotamdavid/appdatabase:latest
          command: ["sh", "-c"]
          args: ["mysql -h 34.27.164.93 -u root -P 3306 -pyotam -D users < /home/yotam/Desktop/docker/ferari_docker/web_project/init.sql"]
          volumeMounts:
            - name: init-script
              mountPath: /home/yotam/Desktop/docker/ferari_docker/web_project/init.sql
              subPath: init.sql
      restartPolicy: Never
      volumes:
        - name: init-script
          configMap:
            name: init-script-configmap
            items:
              - key: init.sql
                path: init.sql
