apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init-job
spec:
  template:
    spec:
      containers:
        - name: mysql-client
          image: mysql:latest
          command: ["/bin/sh", "-c"]
          args: ["mysql -h mysql -u root -pyotam users < /home/yotam/Desktop/k8s/k8s_project/init.sql"]
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: yotam
          volumeMounts:
            - name: init-sql
              mountPath: /home/yotam/Desktop/k8s/k8s_project/init.sql
              subPath: init.sql
      restartPolicy: Never
      volumes:
        - name: init-sql
          configMap:
            name: init-sql-configmap
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: init-sql-configmap
data:
  init.sql: |
    -- הוסף כאן את הפקודות מקובץ ה-init.sql
