apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: "yotamdavid/ferari_website:latest"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
