apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yotamdavid-ferari-website
  template:
    metadata:
      labels:
        app: yotamdavid-ferari-website
    spec:
      containers:
      - name: my-container
        image: yotamdavid/ferari_website:latest
        ports:
        - containerPort: 32000
