apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: yotandavid/ferari_website:latest
  template:
    metadata:
      labels:
        app: yotandavid/ferari_website:latest
    spec:
      containers:
      - name: my-container
        image: nginx:latest
        ports:
        - containerPort: 80
