apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: docker-app
  template:
    metadata:
      labels:
        app: docker-app
    spec:
      containers:
        - name: flask-app
          image: yotamdavid/ferari_website:latest
          ports:
            - containerPort: 5000
